### ISSUE TITLE
Schematics folder needs adding for mod operation

### ISSUE THREAD

**Issue by paramat** [minetest-mods/saveschems#2]
The repo now misses a schematics folder, obviously due to the new gitignore, however this means the mod doesn't work as-is, it needs a folder named 'schematics' adding. This may confuse users. Maybe add a comment about this somewhere? Or is there a way to have the folder present but empty?
Maybe even include the actual schematics in the folder, they're small files.

**Comment by sofar** [comment]
Easiest way is to just have a README.md in the folder. Empty folders in git are problematic.

**Comment by paramat** [comment]
Ok. Although i'd prefer a .txt file.

**Comment by sofar** [comment]
.txt is fine with me

**Comment by paramat** [comment]
I'll sort this out sometime.

**Comment by sofar** [comment]
8887ffc
